# Generated by Django 5.1.1 on 2025-03-27 20:25

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('bioguide_id', models.TextField(help_text='Corresponds to bioguideId in api.congress.gov.', primary_key=True, serialize=False)),
                ('current_party', models.TextField()),
                ('inverted_name', models.TextField(help_text='Inverted version of the full name, i.e. Lastname, Firstname. Should correspond to invertedOrderName in api.congress.gov.')),
                ('lis_id', models.TextField(blank=True, help_text='Senators have an LIS ID that is used instead of the bioguide ID when reporting vote results (unclear why).', null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congress', models.PositiveSmallIntegerField()),
                ('title', models.TextField(blank=True)),
                ('type', models.TextField()),
                ('number', models.PositiveSmallIntegerField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('congress', 'type', 'number'), name='core_bill_congress_number_unique')],
            },
        ),
        migrations.CreateModel(
            name='CongressMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamber', models.TextField(choices=[('senate', 'Senate'), ('house', 'House')])),
                ('congress', models.PositiveSmallIntegerField()),
                ('state', models.TextField()),
                ('district', models.PositiveSmallIntegerField(null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_time', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('vote_count', models.IntegerField(db_default=0, default=0)),
                ('vote_with_democrats_count', models.IntegerField(db_default=0, default=0)),
                ('vote_with_republicans_count', models.IntegerField(db_default=0, default=0)),
                ('democratic_loyalty_rank_in_chamber', models.PositiveSmallIntegerField(db_default=None, default=None, null=True)),
                ('democratic_loyalty_rank_in_party', models.PositiveSmallIntegerField(db_default=None, default=None, null=True)),
                ('republican_loyalty_rank_in_chamber', models.PositiveSmallIntegerField(db_default=None, default=None, null=True)),
                ('republican_loyalty_rank_in_party', models.PositiveSmallIntegerField(db_default=None, default=None, null=True)),
                ('congress_membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.congressmembership')),
            ],
        ),
        migrations.CreateModel(
            name='RollCall',
            fields=[
                ('category', models.TextField()),
                ('chamber', models.TextField(choices=[('senate', 'Senate'), ('house', 'House')])),
                ('congress', models.PositiveSmallIntegerField()),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField()),
                ('question', models.TextField()),
                ('result', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('dem_maj_position', models.TextField(db_default='', default='')),
                ('repub_maj_position', models.TextField(db_default='', default='')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member')),
                ('roll_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rollcall')),
            ],
        ),
        migrations.AddConstraint(
            model_name='congressmembership',
            constraint=models.UniqueConstraint(fields=('chamber', 'member', 'congress'), name='core_congressmembership_chamber_member_congress_unique'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('member', 'roll_call'), name='core_vote_member_rollcall_unique'),
        ),
    ]
